CREATE TABLE IF NOT EXISTS product
(
    product_id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    product_name VARCHAR (250)  NOT NULL,
    description VARCHAR(255)  NOT NULL,
	brand VARCHAR(100)  NOT NULL,
	image_url VARCHAR(255)  NOT NULL,
	price DECIMAL(10, 2)  NOT NULL,
	category VARCHAR(255)  NOT NULL,
	created_at TIMESTAMPTZ  DEFAULT now(),
    updated_at TIMESTAMPTZ  DEFAULT now()
);


CREATE TABLE IF NOT EXISTS review
(
    review_id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ,
    comment VARCHAR(100) NOT NULL,
    rate INTEGER NOT NULL,
    cover VARCHAR(255) NOT NULL,
    product_id INTEGER REFERENCES product,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);